name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: zig build test
      - run: zig fmt --check src/

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        target: [x86_64-linux, x86_64-macos, aarch64-linux]
        optimize: [Debug, ReleaseSafe]

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: Build ${{ matrix.target }} (${{ matrix.optimize }})
        run: |
          zig build --release=${{ matrix.optimize == 'ReleaseSafe' && 'safe' || 'off' }} -Dtarget=${{ matrix.target }}

      - name: Verify binary
        if: matrix.target == 'x86_64-linux'
        run: |
          ./zig-out/bin/fast-cli --help
          file zig-out/bin/fast-cli
